#!/usr/bin/env php

<?php

require __DIR__ . '/../../../../vendor/autoload.php';

use Hgraca\Katas\Patterns\Behavioral\Template\ReportGenerator;

$reportGenerator = new ReportGenerator();

$reportGenerator->generateReport('Sales');

echo "\n\n\n";

$reportGenerator->generateReport('Inventory');
