#!/usr/bin/env php

<?php

require __DIR__ . '/../../../../vendor/autoload.php';

use Hgraca\Katas\Patterns\Behavioral\Strategy\MyService;

$myService = new MyService();

$myService->run('A');
$myService->run('B');
$myService->run('C');
$myService->run();
